spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-migration-naming: false
  application:
    name: store
datasource:
  url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
  username: root
  password: 00138500
stripe:
  apiUrl: https://api.stripe.com
  timeout: 1000
  enabled: true
  supported-currencies: USD,EUR,GBP
payment:
  service: stripe